/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 29 18:40:14 GMT 2022
 */

package org.jsecurity;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsecurity.JSecurityException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JSecurityException_ESTest extends JSecurityException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JSecurityException jSecurityException0 = new JSecurityException((Throwable) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JSecurityException jSecurityException0 = new JSecurityException();
      JSecurityException jSecurityException1 = new JSecurityException("", jSecurityException0);
      assertFalse(jSecurityException1.equals((Object)jSecurityException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JSecurityException jSecurityException0 = new JSecurityException(";");
  }
}
