/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 29 18:42:42 GMT 2022
 */

package org.jsecurity.aop;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.annotation.Annotation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsecurity.authz.aop.AuthenticatedAnnotationHandler;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AnnotationHandler_ESTest extends AnnotationHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuthenticatedAnnotationHandler authenticatedAnnotationHandler0 = new AuthenticatedAnnotationHandler();
      Class<? extends Annotation> class0 = authenticatedAnnotationHandler0.getAnnotationClass();
      assertFalse(class0.isPrimitive());
  }
}
